[package]
name = "paintdice"
version = "0.1.0"
authors = ["Joe Richey <joerichey@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rayon = "1.3"